server:
  port: 8502


spring:
  application:
    name: ticket-service

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microserviceapp
    username: root
    password: microservice-app
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
  rabbitmq:
    username: erayy
    password: erayy
  cloud:
    stream:
      bindings:
        output:
          destination: notification.q
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

